/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tptransversal.vistas;

/**
 *
 * @author Mauro
 */
public class TPTransversalView extends javax.swing.JFrame {

    /**
     * Creates new form TPTransversalView
     */
    public TPTransversalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();
        jMMaterias = new javax.swing.JMenu();
        jMFormularioMaterias = new javax.swing.JMenuItem();
        jMAlumnos = new javax.swing.JMenu();
        jMFormularioAlumnos = new javax.swing.JMenuItem();
        jMInscripciones = new javax.swing.JMenu();
        jMManejoInscripciones = new javax.swing.JMenuItem();
        jMCargaNotas = new javax.swing.JMenu();
        jMManipulacionNotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMListadoAlumnosXMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPLayout = new javax.swing.GroupLayout(jDP);
        jDP.setLayout(jDPLayout);
        jDPLayout.setHorizontalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jDPLayout.setVerticalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jMArchivo.setText("Archivo");

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMArchivo.add(jMSalir);

        jMenuBar1.add(jMArchivo);

        jMMaterias.setText("Materias");

        jMFormularioMaterias.setText("Formulario de Materias");
        jMFormularioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioMateriasActionPerformed(evt);
            }
        });
        jMMaterias.add(jMFormularioMaterias);

        jMenuBar1.add(jMMaterias);

        jMAlumnos.setText("Alumnos");

        jMFormularioAlumnos.setText("Formulario de alumnos");
        jMFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioAlumnosActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMFormularioAlumnos);

        jMenuBar1.add(jMAlumnos);

        jMInscripciones.setText("Inscripciones");

        jMManejoInscripciones.setText("Manejo de inscripciones");
        jMInscripciones.add(jMManejoInscripciones);

        jMenuBar1.add(jMInscripciones);

        jMCargaNotas.setText("Carga de notas");

        jMManipulacionNotas.setText("Manipulación de notas");
        jMCargaNotas.add(jMManipulacionNotas);

        jMenuBar1.add(jMCargaNotas);

        jMConsultas.setText("Consultas");

        jMListadoAlumnosXMateria.setText("Listado de alumnos x materia");
        jMConsultas.add(jMListadoAlumnosXMateria);

        jMenuBar1.add(jMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMFormularioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioMateriasActionPerformed
        jDP.removeAll();
        jDP.repaint();
        MateriasView Materias_view = new MateriasView();
        Materias_view.setVisible(true);
        jDP.add(Materias_view);
        jDP.moveToFront(Materias_view); 
    }//GEN-LAST:event_jMFormularioMateriasActionPerformed

    private void jMFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioAlumnosActionPerformed
        jDP.removeAll();
        jDP.repaint();
        AlumnoView Alumno_view = new AlumnoView();
        Alumno_view.setVisible(true);
        jDP.add(Alumno_view);
        jDP.moveToFront(Alumno_view); 
    }//GEN-LAST:event_jMFormularioAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPTransversalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDP;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenu jMCargaNotas;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMFormularioAlumnos;
    private javax.swing.JMenuItem jMFormularioMaterias;
    private javax.swing.JMenu jMInscripciones;
    private javax.swing.JMenuItem jMListadoAlumnosXMateria;
    private javax.swing.JMenuItem jMManejoInscripciones;
    private javax.swing.JMenuItem jMManipulacionNotas;
    private javax.swing.JMenu jMMaterias;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
